// GENERATED by scripts/generate-images.mjs: do not edit. Source px of each capture and its display width (0.65x).
export const SHOT_SCALE = 0.65;
export const SHOTS = {
  "SBFMainWindow": {
    "w": 860,
    "h": 1124,
    "display": 559
  },
  "SFSymbolBrowser": {
    "w": 1120,
    "h": 1200,
    "display": 728
  },
  "SBFAddFavoriteWindow": {
    "w": 960,
    "h": 1930,
    "display": 624
  },
  "svg-import": {
    "w": 1104,
    "h": 1808,
    "display": 718
  },
  "custom-svg-settings": {
    "w": 1136,
    "h": 2234,
    "display": 738
  },
  "SBFAddFavoriteWithExistingIcon": {
    "w": 1008,
    "h": 2284,
    "display": 655
  },
  "SBFAddFavoriteAdvancedSuccess": {
    "w": 960,
    "h": 2116,
    "display": 624
  },
  "SBFTaskbarPopOver": {
    "w": 584,
    "h": 657,
    "display": 380
  },
  "SBFSettings": {
    "w": 944,
    "h": 1516,
    "display": 614
  },
  "SBFUpdateNotification": {
    "w": 880,
    "h": 1144,
    "display": 572
  },
  "example": {
    "w": 618,
    "h": 740,
    "display": 402
  }
} as const;
export type ShotName = keyof typeof SHOTS;
