// Builds webp variants of the owner's real screenshots (../design/assets, 2x retina windows on the
// vivid wallpaper) plus the app icon sizes. One scale system: every capture renders at 0.65x its pixels
// (1.3x true size), so we emit that width and the full retina width. Metadata goes to src/lib/shots.ts.
import fs from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const root = process.cwd();
const src = path.resolve(root, "../design/assets");
const out = path.join(root, "public/shots");
const imgOut = path.join(root, "public/images");
await fs.mkdir(out, { recursive: true });
await fs.mkdir(imgOut, { recursive: true });

export const SCALE = 0.65;
const NAMES = [
  "SBFMainWindow", "SFSymbolBrowser", "SBFAddFavoriteWindow", "svg-import", "custom-svg-settings",
  "SBFAddFavoriteWithExistingIcon", "SBFAddFavoriteAdvancedSuccess", "SBFTaskbarPopOver", "SBFSettings",
  "SBFUpdateNotification", "example",
];

let count = 0;
const meta = {};
for (const name of NAMES) {
  const file = path.join(src, `${name}.png`);
  const m = await sharp(file).metadata();
  const display = Math.round(m.width * SCALE);
  for (const w of [display, m.width]) {
    const target = path.join(out, `${name}-w${w}.webp`);
    try { await fs.access(target); } catch {
      await sharp(file).resize({ width: w }).webp({ quality: 84, smartSubsample: true }).toFile(target);
      count++;
    }
  }
  meta[name] = { w: m.width, h: m.height, display };
}
const ts = `// GENERATED by scripts/generate-images.mjs: do not edit. Source px of each capture and its display width (0.65x).
export const SHOT_SCALE = ${SCALE};
export const SHOTS = ${JSON.stringify(meta, null, 2)} as const;
export type ShotName = keyof typeof SHOTS;
`;
await fs.writeFile(path.join(root, "src/lib/shots.ts"), ts);

// App icon
const icon = path.join(src, "sidebarfavorites-icon.png");
for (const s of [32, 64, 180, 512]) {
  const target = path.join(imgOut, `icon-${s}.png`);
  try { await fs.access(target); } catch { await sharp(icon).resize(s, s).png({ compressionLevel: 9 }).toFile(target); count++; }
}
console.log(`Generated ${count} image variants; wrote src/lib/shots.ts.`);
