"""Emits src/components/glyphs-sf.tsx: filled SF-style silhouettes as 0..16 viewBox path data.
Run: python3 gen_sf.py > ../src/components/glyphs-sf.tsx"""
import math, json
from shapely.geometry import Polygon, box, MultiPolygon
from shapely.ops import unary_union
from shapely import affinity
from gen_shapes import (rr, circ, ell, line, flat, folder, hammer, note, palette, plane, branch,
                        cloud, camera, doc_mag)

def star():
    pts = []
    for i in range(10):
        r = 92 if i % 2 == 0 else 40
        a = -math.pi / 2 + i * math.pi / 5
        pts.append((r * math.cos(a), r * math.sin(a)))
    return Polygon(pts).buffer(-6, join_style="mitre").buffer(9, quad_segs=12).buffer(-3, quad_segs=12)

def heart():
    g = unary_union([circ(-40, -32, 42), circ(40, -32, 42), Polygon([(-80, -12), (80, -12), (0, 84)]), box(-40, -50, 40, 0)])
    return g.buffer(-6, quad_segs=12).buffer(6, quad_segs=12)

def bookmark():
    return Polygon([(-50, -88), (50, -88), (50, 88), (0, 44), (-50, 88)]).buffer(-5, join_style="mitre").buffer(7, quad_segs=10)

def flag():
    wave = Polygon([(-52, -80), (78, -80), (46, -38), (78, 4), (-52, 4)]).buffer(-4, join_style="mitre").buffer(4, quad_segs=8)
    return unary_union([rr(-74, -88, -50, 90, 10), wave])

def tag():
    body = Polygon([(-88, 0), (-34, -56), (82, -56), (82, 56), (-34, 56)]).buffer(-8, join_style="mitre").buffer(8, quad_segs=10)
    body = body.difference(circ(-40, 0, 12))
    return affinity.rotate(body, -35, origin=(0, 0))

def archive():
    lid = rr(-92, -72, 92, -20, 8)
    body = rr(-78, -8, 78, 76, 10).difference(rr(-26, 12, 26, 30, 8))
    return unary_union([lid, body])

def briefcase():
    body = rr(-92, -40, 92, 78, 14).difference(rr(-12, -2, 12, 16, 5))
    handle = rr(-38, -78, 38, -28, 12).difference(box(-22, -64, 22, -20))
    return unary_union([body, handle])

def folder_fill():
    return folder().difference(flat([(-88, -26), (-10, -26)], 3.2))

SF = [
    ("folder", folder), ("hammer.fill", hammer), ("music.note", note), ("paintpalette", palette),
    ("paperplane.fill", plane), ("arrow.triangle.branch", branch), ("icloud", cloud), ("camera", camera),
    ("doc.text.magnifyingglass", doc_mag),
    ("star.fill", star), ("heart.fill", heart), ("bookmark.fill", bookmark), ("flag.fill", flag),
    ("tag.fill", tag), ("archivebox.fill", archive), ("briefcase.fill", briefcase), ("folder.fill", folder_fill),
]

def fit(g, pad=1.0):
    x0, y0, x1, y1 = g.bounds
    s = (16 - 2 * pad) / max(x1 - x0, y1 - y0)
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    return affinity.translate(affinity.scale(g, s, s, origin=(cx, cy)), 8 - cx, 8 - cy)

def fmt(v):
    s = ("%.2f" % v).rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s

def to_d(g):
    g = g.simplify(0.035)
    polys = list(g.geoms) if isinstance(g, MultiPolygon) else [g]
    out = []
    for p in polys:
        for ring in [p.exterior] + list(p.interiors):
            c = list(ring.coords)[:-1]
            out.append("M" + "L".join("%s %s" % (fmt(x), fmt(y)) for x, y in c) + "Z")
    return "".join(out)

if __name__ == "__main__":
    print('// GENERATED by rive/gen_sf.py: do not edit. Filled SF-style silhouettes, 0..16 viewBox, evenodd.')
    print('export const SF_PATHS: Record<string, { d: string; evenodd?: boolean }> = {')
    for name, fn in SF:
        d = to_d(fit(fn()))
        print('  %s: { d: "%s", evenodd: true },' % (json.dumps(name), d))
    print('};\n')
    print('export function SfGlyph({ name, size = 16, className }: { name: string; size?: number; className?: string }) {')
    print('  const g = SF_PATHS[name];')
    print('  if (!g) return null;')
    print('  return (')
    print('    <svg viewBox="0 0 16 16" width={size} height={size} fill="currentColor" aria-hidden="true" className={className}>')
    print('      <path d={g.d} fillRule={g.evenodd ? "evenodd" : "nonzero"} />')
    print('    </svg>')
    print('  );')
    print('}')
